Added Tests for OpportunitySideCard
Ignitus/Ignitus-client pull request #936
Opened 2020-08-19 16:07 UTC by hrahul2605

PR to issue #931

2020-08-19 18:29 UTC, Dishebh approved these changes

2020-08-19 18:30 UTC, Dishebh commented
@Marvin9 can you pls review this as well?

2020-08-20 04:33 UTC, Marvin9 requested changes
Everything is covered except ```handleClick```, Add one more test case under ```<InfoCard />``` and simulate apply button click to assert the status of ```ApplyStatus``` before and after.

[Here](https://github.com/Ignitus/Ignitus-client/blob/4d58c9193dc1c968cda33dc7decc25904baf0314/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms/ignitus-defaultIconInput/Components/defaultIconInput/index.test.tsx#L42) is the reference to simulate events.

2020-08-20 14:46 UTC, hrahul2605 commented
Added the test @Marvin9 . Please review it

2020-08-21 03:50 UTC, Marvin9 commented on src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-OpportunitySideCard/Components/index.test.tsx
> +  });
```suggestion
  it('should change apply status on Apply button click', () => {
    expect(wrapper.find(S.ApplyStatus).prop('status')).toBe('Apply');
    wrapper
      .find(S.Button)
      .at(0)
      .simulate('click');
    expect(wrapper.find(S.ApplyStatus).prop('status')).toBe('Applied');
  });
```

2020-08-21 10:51 UTC, merged